package jetbrains.mps.logic.reactor.constraint;

/*Generated by MPS */

import java.util.List;
import java.util.Collections;
import java.util.Arrays;
import java.util.ArrayList;

public class AbstractConstraint implements Constraint {

  public AbstractConstraint(ConstraintSymbol constraintSymbol, Object... arguments) {
    this.symbol = constraintSymbol;
    this.arguments = arguments;
  }

  public ConstraintSymbol symbol() {
    return symbol;
  }

  public List<Object> arguments() {
    return Collections.unmodifiableList(Arrays.asList(arguments));
  }

  public List<Class<?>> argumentTypes() {
    ArrayList<Class<?>> types = new ArrayList<Class<?>>(arguments.length);
    for (Object arg : arguments) {
      types.add(arg.getClass());
    }
    return types;
  }

  private ConstraintSymbol symbol;
  private Object[] arguments;
}
