package jetbrains.mps.logic.reactor.constraint;

/*Generated by MPS */


/**
 * A constraint that is provided by a solver. Can be either told or asked for a constraint. 
 */
public interface BuiltinConstraint extends Constraint {

  public Queryable solver(ComputingSession session);

  public Class<? extends Queryable> solverClass();

  public String symbol();

  public int arity();

}
