package jetbrains.mps.logic.reactor.constraint;

/*Generated by MPS */


public interface ComputingTracer {

  public void askSuccess(PredicateSymbol predicateSymbol, Object... args);

  public void askFailure(PredicateSymbol predicateSymbol, Object... args);

  public void reportFailure(String message);

}
