package jetbrains.mps.logic.reactor.constraint;

/*Generated by MPS */


public interface ComputingTracer {

  public void askSuccess(BuiltinConstraint autoConstraint, Object... args);

  public void askFailure(BuiltinConstraint autoConstraint, Object... args);

}
