package jetbrains.mps.logic.reactor.constraint;

/*Generated by MPS */


/**
 * A basic item of computation.
 */
public interface ComputingItem {

  public void init(ComputingSession session, ComputingTracer tracer);

  public void dispose(ComputingSession session);

}
