package jetbrains.mps.logic.reactor.constraint;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.logic.reactor.logical.LogicalContext;

/**
 * A constraint provided by a handler. Can only be told.
 */
public interface Constraint extends AndItem {

  public ConstraintSymbol symbol();

  public List<Class<?>> argumentTypes();

  public ConstraintOccurrence occurrence(LogicalContext context);

}
