package jetbrains.mps.logic.reactor.constraint;

/*Generated by MPS */

import java.util.Collection;

public interface ConstraintOccurrence {

  public Constraint constraint();

  public Collection<?> arguments();

}
