package jetbrains.mps.logic.reactor.constraint;

/*Generated by MPS */

import java.util.List;

public interface ConstraintOccurrence {

  public Constraint constraint();

  public List<Object> arguments();

}
