package jetbrains.mps.logic.reactor.constraint;

/*Generated by MPS */


/**
 * TODO: move to the constraint model
 */
public class ConstraintSymbol extends Symbol {

  public static ConstraintSymbol symbol(String id, int arity) {
    return new ConstraintSymbol(id, arity);
  }

  public ConstraintSymbol(String id, int arity) {
    super(id, arity);
  }

  @Override
  public String toString() {
    return id() + "/" + arity();
  }

}
