package jetbrains.mps.logic.reactor.constraint;

/*Generated by MPS */

import java.util.List;

/**
 * A constraint provided by a handler. Can only be told.
 * FIXME: should be merely a factory for ConstraintOccurrence's
 * FIXME: should be provided by the session (from ConstraintSymbol)
 */
public interface Constraint extends AndItem {

  public ConstraintSymbol symbol();

  public List<Class<?>> argumentTypes();

}
