package jetbrains.mps.logic.reactor.constraint;

/*Generated by MPS */


/**
 * TODO: move to the constraint model
 */
public class ConstraintSymbol {

  public static ConstraintSymbol symbol(String id, int arity) {
    return new ConstraintSymbol(id, arity, false);
  }

  public static ConstraintSymbol builtinSymbol(String id, int arity) {
    return new ConstraintSymbol(id, arity, true);
  }

  private ConstraintSymbol(String id, int arity, boolean builtin) {
    this.id = id;
    this.arity = arity;
    this.builtin = builtin;
  }

  public String id() {
    return id;
  }

  public int arity() {
    return arity;
  }

  public boolean isBuiltin() {
    return builtin;
  }

  @Override
  public String toString() {
    return id;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || this.getClass() != o.getClass()) {
      return false;
    }

    ConstraintSymbol that = (ConstraintSymbol) o;
    if ((id != null ? !(id.equals(that.id)) : that.id != null)) {
      return false;
    }
    if (arity != that.arity) {
      return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 43 * result + ((id != null ? String.valueOf(id).hashCode() : 0));
    result = 31 * result + 37 * arity;
    return result;
  }

  private String id;
  private int arity;

  private boolean builtin;
}
