package jetbrains.mps.logic.reactor.constraint;

/*Generated by MPS */


/**
 * A constraint provided by a handler. Can only be told.
 */
public interface Constraint extends ComputingItem {

  public Instructible handler(ComputingSession session);

  public Class<? extends Instructible> handlerClass();

  public String name();

  public int arity();

}
