package jetbrains.mps.logic.reactor.constraint;

/*Generated by MPS */


public class JavaPredicateSymbol extends PredicateSymbol {

  public JavaPredicateSymbol(String expression, int arity) {
    super(expression, arity);
  }

  @Override
  public String toString() {
    return "J:" + id() + "/" + arity();
  }
}
