package jetbrains.mps.logic.reactor.constraint;

/*Generated by MPS */

import jetbrains.mps.logic.reactor.logical.LogicalContext;

public class JavaPredicate extends AbstractPredicate {

  private JavaPredicateSymbol symbol;

  public JavaPredicate(JavaPredicateSymbol predicateSymbol, String id, Object... args) {
    super(args);
    this.id = id;
    this.symbol = predicateSymbol;
  }

  public String id() {
    return id;
  }

  public PredicateSymbol symbol() {
    return symbol;
  }

  @Override
  public PredicateInvocation invocation(LogicalContext logicalContext) {
    // FIXME: implement me 
    throw new UnsupportedOperationException("not implemented");
  }

  private String id;
}
