package jetbrains.mps.logic.reactor.constraint;

/*Generated by MPS */


public class JavaPredicate extends AbstractPredicate {

  private JavaPredicateSymbol symbol;

  public JavaPredicate(JavaPredicateSymbol predicateSymbol, String id, Object... args) {
    super(args);
    this.id = id;
    this.symbol = predicateSymbol;
  }

  public String id() {
    return id;
  }

  public PredicateSymbol symbol() {
    return symbol;
  }
  private String id;
}
