package jetbrains.mps.logic.reactor.constraint;

/*Generated by MPS */

import java.util.Collection;

public interface PredicateInvocation {

  public Predicate predicate();

  public Collection<?> arguments();

}
