package jetbrains.mps.logic.reactor.constraint;

/*Generated by MPS */

import jetbrains.mps.logic.reactor.logical.LogicalContext;

/**
 * A predicate that is provided by a solver. Can be either told or asked. 
 */
public interface Predicate extends AndItem {

  public PredicateSymbol symbol();

  public PredicateInvocation invocation(LogicalContext logicalContext);

}
