package jetbrains.mps.logic.reactor.constraint;

/*Generated by MPS */


public class StandardBuiltinConstraint {

  public static final ConstraintSymbol UNIFICATION = ConstraintSymbol.builtinSymbol("=", 2);

  public static final ConstraintSymbol EQUALS = ConstraintSymbol.builtinSymbol("==", 2);

  public static final ConstraintSymbol ASSERT = ConstraintSymbol.builtinSymbol("assert", 1);

  public static final ConstraintSymbol FREE = ConstraintSymbol.builtinSymbol("isVar", 1);

  public static final ConstraintSymbol BOUND = ConstraintSymbol.builtinSymbol("isNonVar", 1);

}
