package jetbrains.mps.logic.reactor.constraint;

/*Generated by MPS */


public abstract class Symbol {

  protected Symbol(String id, int arity) {
    this.id = id;
    this.arity = arity;
  }

  public String id() {
    return id;
  }

  public int arity() {
    return arity;
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 43 * result + ((id != null ? String.valueOf(id).hashCode() : 0));
    result = 31 * result + 37 * arity;
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || this.getClass() != o.getClass()) {
      return false;
    }

    Symbol that = (Symbol) o;
    if ((id != null ? !(id.equals(that.id())) : that.id != null)) {
      return false;
    }
    if (arity != that.arity) {
      return false;
    }

    return true;
  }

  private String id;
  private int arity;
}
