package jetbrains.mps.logic.reactor.rule;

/*Generated by MPS */


public class InvalidRuleException extends Exception {

  public InvalidRuleException(String message) {
    super(message);
  }

  public InvalidRuleException(String message, Throwable throwable) {
    super(message, throwable);
  }

}
