package jetbrains.mps.logic.reactor.rule;

/*Generated by MPS */

import jetbrains.mps.logic.reactor.constraint.occurrence.ConstraintOccurrence;
import jetbrains.mps.logic.reactor.constraint.occurrence.AbstractConstraintOccurrence;

public abstract class Rule {

  public abstract Rule.Kind kind();

  public abstract String tag();

  public abstract Iterable<ConstraintOccurrence> headKept();

  public abstract Iterable<ConstraintOccurrence> headReplaced();

  public abstract Iterable<AbstractConstraintOccurrence> guard();

  public abstract Iterable<AbstractConstraintOccurrence> body();

  public abstract Iterable<AbstractConstraintOccurrence> all();

  public static   enum Kind {
    SIMPLIFICATION(),
    PROPAGATION(),
    SIMPAGATION();

  }

}
