package jetbrains.mps.logic.reactor.constraint.occurrence;

/*Generated by MPS */

import jetbrains.mps.logic.reactor.constraint.ConstraintSymbol;

public class BuiltinConstraintOccurrence extends AbstractConstraintOccurrence {

  public static BuiltinConstraintOccurrence unitary(ConstraintSymbol symbol, Object arg) {
    if (symbol.arity() != 1) {
      throw new IllegalArgumentException("arity mismatch");
    }

    return new BuiltinConstraintOccurrence(symbol, arg);
  }

  public static BuiltinConstraintOccurrence binary(ConstraintSymbol symbol, Object arg1, Object arg2) {
    if (symbol.arity() != 2) {
      throw new IllegalArgumentException("arity mismatch");
    }

    return new BuiltinConstraintOccurrence(symbol, arg1, arg2);
  }

  @Override
  public ConstraintKind kind() {
    return ConstraintKind.BUILTIN;
  }

  private BuiltinConstraintOccurrence(ConstraintSymbol symbol, Object... arg) {
    super(symbol, arg);
  }

}
