package jetbrains.mps.logic.reactor.constraint.occurrence;

/*Generated by MPS */


public class InvalidConstraintException extends Exception {

  public InvalidConstraintException(String message) {
    super(message);
  }

  public InvalidConstraintException(String message, Throwable ex) {
    super(message, ex);
  }

}
