package jetbrains.mps.logic.reactor.constraint.occurrence;

/*Generated by MPS */

import jetbrains.mps.logic.reactor.constraint.ConstraintSymbol;

public class JavaConstraintOccurrence extends AbstractConstraintOccurrence {

  public static JavaConstraintOccurrence nary(String template, Object... args) {
    return new JavaConstraintOccurrence(template, args);
  }

  private JavaConstraintOccurrence(String template, Object... args) {
    super(ConstraintSymbol.symbol(template, args.length), args);
  }

  public ConstraintKind kind() {
    return ConstraintKind.JAVA;
  }

  public String toJavaString() {
    return String.valueOf(symbol());
  }

}
