package jetbrains.mps.logic.reactor.constraint.occurrence;

/*Generated by MPS */

import jetbrains.mps.logic.reactor.constraint.StandardBuiltinConstraint;
import jetbrains.mps.logic.reactor.constraint.ConstraintSymbol;

public class LogicalConstraintOccurence extends AbstractConstraintOccurrence {

  public static LogicalConstraintOccurence bound(Object logical) {
    return new LogicalConstraintOccurence(StandardBuiltinConstraint.BOUND, logical);
  }

  public static LogicalConstraintOccurence free(Object logical) {
    return new LogicalConstraintOccurence(StandardBuiltinConstraint.FREE, logical);
  }

  private LogicalConstraintOccurence(ConstraintSymbol symbol, Object logical) {
    super(symbol, logical);
  }

  public ConstraintKind kind() {
    return ConstraintKind.LOGICAL;
  }

}
