package jetbrains.mps.coderules.ideaplugin;

/*Generated by MPS */

import jetbrains.mps.annotations.GeneratedClass;

@GeneratedClass(node = "r:835f8ea3-a800-4588-a80b-1de6d47c2098(jetbrains.mps.coderules.ideaplugin)/3625063056952761380", model = "r:835f8ea3-a800-4588-a80b-1de6d47c2098(jetbrains.mps.coderules.ideaplugin)")
public class CoderulesOptions {
  public static final String PREFIX = "mps.coderules.";

  public static final String OPTION_PROFILING_ENABLED = PREFIX + "profiling";

  public static final Config.Option<Boolean> PROFILING_ENABLED = new Config.Option<Boolean>() {
    @Override
    public Boolean get(Config config) {
      return (Boolean) config.getOption(OPTION_PROFILING_ENABLED);
    }
  };

  public static void registerDefaultProviders(Config config) {
    config.registerProvider(Config.Level.USER, PREFIX, (String key) -> {

      if (OPTION_PROFILING_ENABLED.equals(key)) {
        return Boolean.valueOf(System.getProperty(OPTION_PROFILING_ENABLED, "false"));

      }

      return null;
    });
  }

}
