package jetbrains.mps.coderules.ideaplugin;

/*Generated by MPS */

import java.util.Map;
import jetbrains.mps.internal.collections.runtime.MapSequence;

public class TypecheckingOptions {
  public static final String PREFIX = "mps.coderules.typechecking.";

  public static final String OPTION_TYPECHECKING_ENABLED = "mps.coderules.typechecking.enabled";
  public static final String OPTION_TYPECHECKING_WATCHING = "mps.coderules.typechecking.watching";
  public static final String OPTION_TYPECHECKING_REPORTING = "mps.coderules.typechecking.report";
  public static final String OPTION_TYPECHECKING_TRACE = "mps.coderules.typechecking.trace";

  public static final Config.Option<Boolean> TYPECHECKING_ENABLED = new Config.Option<Boolean>() {
    @Override
    public Boolean get(Config config) {
      return (Boolean) config.getOption(OPTION_TYPECHECKING_ENABLED);
    }
  };
  public static final Config.Option<Boolean> TYPECHECKING_WATCHING = new Config.Option<Boolean>() {
    @Override
    public Boolean get(Config config) {
      return (Boolean) config.getOption(OPTION_TYPECHECKING_WATCHING);
    }
  };
  public static final Config.Option<Boolean> TYPECHECKING_REPORTING = new Config.Option<Boolean>() {
    @Override
    public Boolean get(Config config) {
      return (Boolean) config.getOption(OPTION_TYPECHECKING_REPORTING);
    }
  };
  public static final Config.Option<Boolean> TYPECHECKING_TRACE = new Config.Option<Boolean>() {
    @Override
    public Boolean get(Config config) {
      return (Boolean) config.getOption(OPTION_TYPECHECKING_TRACE);
    }
  };
  public static final Config.Option<Boolean> COLLECT_TRACES = new Config.Option<Boolean>() {
    @Override
    public Boolean get(Config config) {
      if (Boolean.TRUE != config.getOption(OPTION_TYPECHECKING_REPORTING)) {
        return Boolean.FALSE;
      }
      return (Boolean) config.getOption(OPTION_TYPECHECKING_TRACE);
    }
  };

  private static Config USER_CONFIG;

  private TypecheckingOptions() {
  }

  public static Config getUserConfig() {
    if (USER_CONFIG == null) {
      USER_CONFIG = Config.create();
      registerDefaultProviders(USER_CONFIG);
    }
    return USER_CONFIG;
  }

  public static Config getParamConfig(Map<String, Object> paramMap) {
    Config config = getUserConfig().copy();
    registerParamMapProvider(config, paramMap);
    return config;
  }

  private static void registerDefaultProviders(Config config) {
    CoderulesOptions.registerDefaultProviders(config);

    config.registerProvider(Config.Level.USER, PREFIX, (String key) -> {

      if (OPTION_TYPECHECKING_ENABLED.equals(key)) {
        return Boolean.valueOf(System.getProperty(OPTION_TYPECHECKING_ENABLED, "false"));

      }

      if (OPTION_TYPECHECKING_WATCHING.equals(key)) {
        return Boolean.valueOf(System.getProperty(OPTION_TYPECHECKING_WATCHING, "false"));

      }

      if (OPTION_TYPECHECKING_REPORTING.equals(key)) {
        return Boolean.valueOf(System.getProperty(OPTION_TYPECHECKING_REPORTING, "false"));

      }

      if (OPTION_TYPECHECKING_TRACE.equals(key)) {
        return Boolean.valueOf(System.getProperty(OPTION_TYPECHECKING_TRACE, "false"));

      }

      return null;
    });
  }

  public static void registerParamMapProvider(Config config, final Map<String, Object> paramMap) {
    config.registerProvider(Config.Level.UI, PREFIX, (String key) -> {

      if (OPTION_TYPECHECKING_ENABLED.equals(key)) {

        return (MapSequence.fromMap(paramMap).get(OPTION_TYPECHECKING_ENABLED) != null ? MapSequence.fromMap(paramMap).get(OPTION_TYPECHECKING_ENABLED) : false);
      }

      if (OPTION_TYPECHECKING_WATCHING.equals(key)) {
        return (MapSequence.fromMap(paramMap).get(OPTION_TYPECHECKING_WATCHING) != null ? MapSequence.fromMap(paramMap).get(OPTION_TYPECHECKING_WATCHING) : false);

      }

      if (OPTION_TYPECHECKING_REPORTING.equals(key)) {
        return (MapSequence.fromMap(paramMap).get(OPTION_TYPECHECKING_REPORTING) != null ? MapSequence.fromMap(paramMap).get(OPTION_TYPECHECKING_REPORTING) : false);

      }

      if (OPTION_TYPECHECKING_TRACE.equals(key)) {
        return (MapSequence.fromMap(paramMap).get(OPTION_TYPECHECKING_TRACE) != null ? MapSequence.fromMap(paramMap).get(OPTION_TYPECHECKING_TRACE) : false);

      }

      return null;
    });
  }

}
