package jetbrains.mps.logic.reactor.program;

/*Generated by MPS */

import java.util.List;

/**
 *  An abstract conjunct. 
 */
public interface AndItem {

  Symbol symbol();

  List<?> arguments();

}
