package jetbrains.mps.logic.reactor.program;

/*Generated by MPS */

import java.util.List;

/**
 * A constraint provided by a handler. Can only be told.
 */
public interface Constraint extends AndItem {

  public ConstraintSymbol symbol();

  public List<Class<?>> argumentTypes();

}
