package jetbrains.mps.logic.reactor.program;

/*Generated by MPS */

import java.util.Collection;
import jetbrains.mps.logic.reactor.logical.LogicalContext;

/**
 * A predicate that is provided by a solver. Can be either told or asked. 
 */
public interface Predicate extends AndItem {

  public PredicateSymbol symbol();

  public Collection<?> invocationArguments(LogicalContext logicalContext);


}
