package jetbrains.mps.logic.reactor.program;

/*Generated by MPS */


/**
 * A predicate that is provided by a solver. Can be either told or asked. 
 */
public interface Predicate extends AndItem {

  public PredicateSymbol symbol();

}
