package jetbrains.mps.logic.reactor.program;

/*Generated by MPS */

import jetbrains.mps.logic.reactor.evaluation.SessionSolver;
import java.util.List;

public abstract class Program {

  public abstract String name();

  public abstract SessionSolver sessionSolver();

  public abstract Iterable<ConstraintSymbol> constraintSymbols();

  public abstract List<Class<?>> constraintArgumentTypes(ConstraintSymbol constraintSymbol);

  public abstract Iterable<PredicateSymbol> predicateSymbols();

  public abstract Iterable<Rule> rules();


}
