package jetbrains.mps.logic.reactor.program;

/*Generated by MPS */

import jetbrains.mps.logic.reactor.evaluation.SessionSolver;

public abstract class ProgramBuilder {

  public abstract Program program(String name, SessionSolver sessionSolver);

  public abstract void addRule(Rule rule) throws InvalidRuleException;

  public abstract Constraint constraint(ConstraintSymbol symbol, Object... args);

  public abstract Predicate predicate(PredicateSymbol symbol, Object... args);

}
