package jetbrains.mps.logic.reactor.program;

/*Generated by MPS */


public abstract class Rule {

  public abstract Rule.Kind kind();

  public abstract String tag();

  public abstract Iterable<Constraint> headKept();

  public abstract Iterable<Constraint> headReplaced();

  public abstract Iterable<Predicate> guard();

  @Deprecated
  public abstract Iterable<AndItem> body();

  public abstract Iterable<? extends Iterable<AndItem>> bodyAlternation();

  public abstract Iterable<AndItem> all();

  public enum Kind {
    SIMPLIFICATION(),
    PROPAGATION(),
    SIMPAGATION()
  }

}
