package jetbrains.mps.logic.reactor.logical;

/*Generated by MPS */


public interface ILogical<T> {

  public String name();

  public String name(NamingContext namingContext);

  public ILogical<T> findRoot();

  public T value();

  public boolean isBound();

  public boolean isWildcard();

}
