package jetbrains.mps.logic.reactor.logical;

/*Generated by MPS */


public interface LogicalPattern<V> {

  public String name();

  public String name(NamingContext namingContext);

  public boolean isWildcard();

  public Class<V> type();

  public Logical<V> instance();

}
