package jetbrains.mps.logic.reactor.logical;

/*Generated by MPS */

/**
 * Substitution of logicals for meta-logicals.
 */
public interface LogicalContext {


  <V> Logical<V> variable(MetaLogical<V> metaLogical);

}
