package jetbrains.mps.logic.reactor.logical;

/*Generated by MPS */


public interface Logical<T> {

  public String name();

  public Logical<T> findRoot();

  public T value();

  public boolean isBound();

  public boolean isWildcard();

  public LogicalPattern<Logical<T>> pattern();

}
