package jetbrains.mps.logic.reactor.logical;

/*Generated by MPS */


/**
 * A run-time representation of a logical variable.
 *
 * @param <T> the value type
 */
public interface Logical<T> {

  String name();

  /**
   * Returns the representative logical instance. 
   * 
   * TODO: rename to 'find()'
   */
  Logical<T> findRoot();

  /**
   * Returns the value associated with this logical instance. 
   * Can be null. 
   * Only the logical instance that is a representative can have value that is not null.
   * 
   * FIXME: must return the representative's value
   */
  T value();

  /**
   * True iff the representative has a non-null value.
   */
  boolean isBound();

  boolean isWildcard();

  MetaLogical<T> metaLogical();

}
