package jetbrains.mps.logic.reactor.logical;

/*Generated by MPS */


public class MetaLogical<V> {

  private static final String WILDCARD = "_";

  public MetaLogical(String name, Class<V> type) {
    this.name = name;
    this.type = type;
  }

  public MetaLogical(Class<V> type) {
    this.name = MetaLogical.WILDCARD + System.identityHashCode(this);
    this.type = type;
    this.wildcard = true;
  }

  public String name() {
    return name;
  }

  public boolean isWildcard() {
    return wildcard;
  }

  public Class<V> type() {
    return type;
  }

  private String name;
  private Class<V> type;
  private boolean wildcard = false;

}
