package jetbrains.mps.logic.reactor.logical;

/*Generated by MPS */


/**
 * A declaration of a logical variable.  
 * @param <T> the value type
 */
public class MetaLogical<T> {

  private static final String WILDCARD = "_";

  public MetaLogical(String name, Class<T> type) {
    this.name = name;
    this.type = type;
  }

  public MetaLogical(Class<T> type) {
    this.name = MetaLogical.WILDCARD + System.identityHashCode(this);
    this.type = type;
    this.wildcard = true;
  }

  public String name() {
    return name;
  }

  public boolean isWildcard() {
    return wildcard;
  }

  public Class<T> type() {
    return type;
  }

  @Override
  public String toString() {
    return name;
  }

  private String name;
  private Class<T> type;
  private boolean wildcard = false;

}
