package jetbrains.mps.logic.reactor.logical;

/*Generated by MPS */


public interface MultiLogicalPattern extends LogicalPattern {

  public int cardinality();

  public LogicalPattern patternAt(int idx);

  public LogicalPattern[] toArray();

}
