package jetbrains.mps.logic.reactor.logical;

/*Generated by MPS */

import java.util.List;
import java.util.ArrayList;

public class MultiMetaLogical<V> extends MetaLogical<V> {

  public MultiMetaLogical(String name, Class<V> type, int cardinality) {
    super(name, type);
    this.cardinality = cardinality;
    init();
  }

  public int cardinality() {
    return cardinality;
  }

  public MetaLogical<V> logicalAt(int idx) {
    return metaLogicals.get(idx);
  }

  public MetaLogical[] toArray() {
    MetaLogical[] array = new MetaLogical[cardinality];
    return metaLogicals.toArray(array);
  }

  private void init() {
    for (int i = 0; i < cardinality; i++) {
      metaLogicals.add(new MetaLogical<V>(name() + "_" + (i + 1), type()));
    }
  }

  private int cardinality;
  private List<MetaLogical<V>> metaLogicals = new ArrayList<MetaLogical<V>>();
}
