package jetbrains.mps.logic.reactor.logical;

/*Generated by MPS */


public interface MultiLogicalPattern<V> extends LogicalPattern<V> {

  public int cardinality();

  public LogicalPattern<V> patternAt(int idx);

  public LogicalPattern[] toArray();

}
