package jetbrains.mps.logic.reactor.logical;

/*Generated by MPS */

import java.util.List;
import java.util.ArrayList;

/**
 * A declaration of a logical variable with index. 
 * @param <T>
 */
public class MultiMetaLogical<T> extends MetaLogical<T> {

  public MultiMetaLogical(String name, Class<T> type, int cardinality) {
    super(name, type);
    this.cardinality = cardinality;
    init();
  }

  public int cardinality() {
    return cardinality;
  }

  public MetaLogical<T> logicalAt(int idx) {
    return metaLogicals.get(idx);
  }

  public MetaLogical[] toArray() {
    MetaLogical[] array = new MetaLogical[cardinality];
    return metaLogicals.toArray(array);
  }

  private void init() {
    for (int i = 0; i < cardinality; i++) {
      metaLogicals.add(new MetaLogical<T>(name() + "_" + (i + 1), type()));
    }
  }

  private int cardinality;
  private List<MetaLogical<T>> metaLogicals = new ArrayList<MetaLogical<T>>();
}
