package jetbrains.mps.logic.reactor.logical;

/*Generated by MPS */

import java.util.Map;
import java.util.HashMap;
import java.util.IdentityHashMap;

public class NamingContext {

  public String uniqueName(ILogical logical) {
    if (!(cachedUnique.containsKey(logical))) {
      cachedUnique.put(logical, makeUnique(logical.name()));
    }
    return cachedUnique.get(logical);
  }

  private String makeUnique(String name) {
    int c = getAndIncrementCounter(name);
    return (c == 0 ? name : name + c);
  }

  private int getAndIncrementCounter(String name) {
    Integer c = (uniqueCounters.containsKey(name) ? uniqueCounters.get(name) : 0);
    uniqueCounters.put(name, c + 1);
    return c;
  }

  private Map<String, Integer> uniqueCounters = new HashMap<String, Integer>();

  private Map<ILogical, String> cachedUnique = new IdentityHashMap<ILogical, String>();

}
