package jetbrains.mps.logic.reactor.logical;

/*Generated by MPS */

import java.util.Map;
import java.util.HashMap;
import java.util.IdentityHashMap;

public class NamingContext {

  public String uniqueName(Logical logical) {
    return cachedOrMakeUnique(logical, logical.name());
  }

  public String uniqueName(LogicalPattern logical) {
    return cachedOrMakeUnique(logical, logical.name());
  }

  private String cachedOrMakeUnique(Object named, String name) {
    if (!(cachedUnique.containsKey(named))) {
      cachedUnique.put(named, makeUnique(name));
    }
    return cachedUnique.get(named);
  }

  private String makeUnique(String name) {
    int c = getAndIncrementCounter(name);
    return (c == 0 ? name : name + c);
  }

  private int getAndIncrementCounter(String name) {
    Integer c = (uniqueCounters.containsKey(name) ? uniqueCounters.get(name) : 0);
    uniqueCounters.put(name, c + 1);
    return c;
  }

  private Map<String, Integer> uniqueCounters = new HashMap<String, Integer>();

  private Map<Object, String> cachedUnique = new IdentityHashMap<Object, String>();

}
