package jetbrains.mps.logic.reactor.logical;

/*Generated by MPS */


public interface SolverLogical<T> extends Logical<T> {

  public SolverLogical<T> findRoot();

  public void setParent(SolverLogical<T> parent);

  public void setValue(T newValue);

  public int rank();

  public void incRank();

  public void mergeObservers(SolverLogical<T> mergeFrom);

}
