package jetbrains.mps.logic.reactor.logical;

/*Generated by MPS */


public interface SolverLogical<T> extends Logical<T> {

  /**
   * Covariant override.
   */
  SolverLogical<T> findRoot();

  /**
   * Unions two equivalence classes of logicals. 
   * Both the receiver and the {@code other} parameter are expected to be representatives.
   * The one with the highest rank becomes the representative for the new class.
   */
  void union(SolverLogical<T> other, SolverLogical.ValueReconciler<T> reconciler);

  /**
   * Calls {@link jetbrains.mps.logic.reactor.logical.SolverLogical#union(SolverLogical<T>, SolverLogical.ValueReconciler<T>) } with the default value reconciler.
   * The default reconciler throws {@link java.lang.IllegalArgumentException } if the two values are not equal.
   */
  void union(SolverLogical<T> other);

  /**
   * Should only be called on a representative. 
   */
  void setValue(T newValue);

  interface ValueReconciler<T> {

    void reconcile(T valueA, T valueB);

  }

}
